default:
    trainer: ppo
    batch_size: 2048
    beta: 5.0e-3
    buffer_size: 20480
    epsilon: 0.2
    hidden_units: 2
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 1e7
    learning_rate_schedule: linear
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    keep_checkpoints: 5
    threaded: true
    checkpoint_interval: 500000
    summary_freq: 50000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
            learning_rate: 3.0e-4

Racing:
    trainer_type: ppo
    hyperparameters:
      batch_size: 120
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 500000000
    time_horizon: 1000
    summary_freq: 12000
    threaded: true
